### ISSUE TITLE
[Feature request] Removing the "title bar" 

### ISSUE THREAD

**Issue by RanzerScore90** [Vencord/Vesktop#106]
the unnecessary space on the top annoys me and you could save some space by taking it off
![image](https://github.com/Vencord/Vesktop/assets/125395197/4ab889d2-330c-4b54-8546-d3d3055647ec)

There's a high chance it's not possible tho and if so, oh well.

**Comment by ImLvna** [comment]
css:

**Comment by kckarnige** [comment]
Learn it

**Comment by viacoro** [comment]
just add the following as a theme or to QuickCSS:
`.withFrame-2dL45i{
	display: none;
}`

**Comment by kckarnige** [comment]
Made a little snippet that makes it apart of the toolbar, like Discord old UI, you're welcome :)
```css
[class*="withFrame-"][class*="titleBar-"] {
    height: 0%;
    margin-top: 0px;
}

[class*="withFrame-"][class*="titleBar-"] > [class*="wordmark-"] {
    display: none;
}

[class*="withFrame-"][class*="titleBar-"] > [class*="winButton-"] {
    width: 40px;
    height: 52px;
}

[class*="upperContainer-"] > [class*="toolbar-"] {
    margin-right: 120px;
}
```
![image](https://github.com/Vencord/Vesktop/assets/32397453/e7b034d5-c82a-457f-9adf-3e7bfe534ac2)

**Comment by kckarnige** [comment]
@RanzerScore90
I made a little snippet that makes it apart of the toolbar, like Discord old UI, you're welcome :)
```css
[class*="withFrame-"][class*="titleBar-"] {
    height: 0%;
    margin-top: 0px;
}

[class*="withFrame-"][class*="titleBar-"] > [class*="wordmark-"] {
    display: none;
}

[class*="withFrame-"][class*="titleBar-"] > [class*="winButton-"] {
    width: 40px;
    height: 52px;
}

[class*="upperContainer-"] > [class*="toolbar-"] {
    margin-right: 120px;
}
```
![image](https://github.com/Vencord/Vesktop/assets/32397453/e7b034d5-c82a-457f-9adf-3e7bfe534ac2)
